name: My BuffTomo monster
on:
  schedule:
    - cron: '23 */6 * * *'   # every 6h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: YuriGuernsey/BuffTomo@main
        with:
          username: yuriguernsey
          monster: beastor               # beastor | drako | pumpkin | neko | shadow | random
          timezone-offset-minutes: "60"  # Guernsey: 60 in summer (BST), 0 in winter
